### ISSUE TITLE
Stray fairies duplication on cycle reset

### ISSUE THREAD

**Issue by Valensfd37** [Z3DR/MM3D_Randomizer#68]
Hi, I've noticed a kind of exploit with the stray fairies.
The stray fairies counter doesn't appear to reset between cycle, and I assume that's on purpose like with the small and boss keys, but now the issues is that some stray fairies do get reset to their locations, specifically it seems to affect all but the bubble fairies.

I managed to get up to 17 fairies in snowhead when I realized.
This could basically allow anyopne to get the fairy reward very early in a dungeon (from the very first for great bay ) simply by doing 15 cycles reset.

Again I don't know if it is on purpose, so either the issue is the drops and chest fairies respawning when they shouldn't or the bubble fairies not respawning when they should.

**Comment by PhlexPlexico** [comment]
Hi,

Yes, this is intentional as of right now. We do not reset fairy counts, keys, or dungeon items on cycle resets, as we do not expect users to go back and collect keys for dungeons. This (as of right now) has the fun side effect of stray fairy chests being able to respawn on cycle reset. 

Since flags and chests exist in different flags, we can disable the stray fairies that are free standing from spawning. If you really wish to cheese your own run with 15 cycle resets, I mean feel free to. But this has already been reported and will be adjusted in future releases.

Thanks!
