### ISSUE TITLE
Logic issue with Gilded Sword check

### ISSUE THREAD

**Issue by Valensfd37** [Z3DR/MM3D_Randomizer#70]
Hi!

So during my last glitchlees logic seed on v1.3.0-06d232 (Citra, MM3D V1.0) I came across what seems like a logic issue.
The logic expect me to get the item behind the gilded sword check, beat snowhead an get the powder keg from one of the spring only chests. 
My issue is that I can't get the prompt to give the gold dust to the smithy because they want me to have done the razor sword check first and my two wallets upgrade are in Great bay and Ikana.

It seems the logic thinks I should be able to deliver the gold dust directly (like with the MM n64 randomizer)

I included the spoiler log just in case.

Thanks !
[463820288 (Bottled Big Poe, Bottled Zora Egg, Hero's Bow, Town Deed, Great Fairy Sword)-spoilerlog.zip](https://github.com/Z3DR/MM3D_Randomizer/files/14515504/463820288.Bottled.Big.Poe.Bottled.Zora.Egg.Hero.s.Bow.Town.Deed.Great.Fairy.Sword.-spoilerlog.zip)

**Comment by Tacoman369** [comment]
Hello,

Currently Logic does not consider that you need to do the razor sword upgrade first before doing the gilded sword check. This will be fixed in the next release.

As a side note, since stray fairies are not included yet you do not need to exclude the individual locations, only the great fairy reward for collecting all of them (assuming you want shuffled great fairy rewards but do not want to collect all the fairies)

Thanks for your report!
