### ISSUE TITLE
Starting a quest and resetting locks the check

### ISSUE THREAD

**Issue by livingbeast** [Z3DR/MM3D_Randomizer#84]
I noticed that if i were to start a quest (mystery milk for example) and playing song of time to start the cycle over, it locks completion and the check that follows.

Edit: Probably not the best way to word that in my opinion. Another example: if I were to start Anju and Kafei, get the letter to Kafei and reset before putting the letter in the mailbox, that quest is locked as well.

**Comment by PhlexPlexico** [comment]
Hi,

I'm not really seeing the issue here? This is vanilla behaviour from the game, and you can still retrieve the trade items from where you got them.

Trade items are also stored on cycle resets as well, and can be swapped with L/R on the gear screen.

Just curious, what version of the randomizer are you currently running? This can be shown by uploading the spoiler log.

Thanks!

**Comment by livingbeast** [comment]
It appears I completely misunderstood everything from the beginning...
I'm sorry for the waste of time.
(to answer the questions though, i am running version 1.3.0 on my 3ds and dont know where the spoiler log is generated on the sd card.)

**Comment by PhlexPlexico** [comment]
No worries! The Spoiler log is located at`/3ds/mm3dr/spoiler_logs` and will have the hash that matches up in the game menu.

But I hope this knowledge helps you finish your seed!
